- name: "Create directory {{ ansible_env.HOME}}/.fonts"
  file: path={{ ansible_env.HOME }}/.fonts state=directory mode=0755 owner={{ansible_user}} group={{ ansible_user }}

- name: "Create directory {{ workspace }}"
  file: path={{ workspace }} state=directory mode=0755 owner={{ansible_user}} group={{ ansible_user }}

- name: "Create directory structure in {{ workspace }}"
  file: path={{ workspace }}/{{ item }} state=directory mode=0755 owner={{ansible_user}} group={{ ansible_user }}
  with_items:
    - pkg
    - bin
    - bashrc.d

- name: "Install bashrc"
  template: src=bashrc.j2 dest={{ ansible_env.HOME}}/.bashrc

- name: "Install {{workspace}}/bashrc.d/theme"
  template: src=bashrcd_theme.j2 dest={{ workspace }}/bashrc.d/theme

- name: "Clone repo solarized xresources"
  git: repo=https://github.com/solarized/xresources.git dest={{ workspace }}/pkg/solarized-xresources

- name: "Clone repo dircolors-solarized"
  git: repo=https://github.com/seebi/dircolors-solarized.git dest={{ workspace }}/pkg/dircolors-solarized
  
- name: "Clone repo Fira font"
  git: repo=https://github.com/mozilla/Fira.git dest={{ workspace }}/pkg/Fira
  register: fira

- name: "Install Fira font"
  copy: src={{ workspace }}/pkg/Fira/ttf/ dest=/home/{{ ansible_user }}/.fonts
  when: fira.changed

- name: "Set mono space font"
  shell: gsettings set org.gnome.desktop.interface monospace-font-name 'Fira Mono Regular 14'

- name: "Install desktop applications"
  become: yes
  apt: name={{ item }}
  with_items:
    - corebird
    - vlc
